name: ci

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  pipeline:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    uses: ./.github/workflows/build-and-test.yml
    with:
      os: ${{ matrix.os }}
