name: build-toolchain
description: Build a Go toolchain and upload it as an artifact.
inputs:
  os:
    description: Runner OS label used in artifact and cache keys.
    required: true
  toolchain:
    description: Which toolchain to build (head or gotip).
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 1.25.x
        # setup-go does caching by default, and issues a warning due to being
        # unable to locate a 'go.sum' for this build. Since we manage caching explicitly,
        # disable setup-go's automatic caching.
        cache: false
    # For 'head', the caller must checkout the repo before using this action.
    # For 'gotip', we checkout golang/go into a subdirectory.
    - uses: actions/checkout@v6
      if: inputs.toolchain == 'gotip'
      with:
        repository: golang/go
        path: go
    # Cache the build artifacts from the stdlib build
    # so that downstream operations don't need to rebuild
    # parts of the stdlib.
    - uses: actions/cache@v5
      with:
        path: .cache/go-build
        key: go-cache-${{ inputs.toolchain }}-${{ inputs.os }}
    - name: Build (unix)
      if: runner.os != 'Windows'
      shell: bash
      # make.bash cannot be invoked from other directories.
      working-directory: go/src
      run: ./make.bash
    - name: Build (windows)
      if: runner.os == 'Windows'
      shell: pwsh
      # .\make.bat cannot be invoked from other directories.
      working-directory: go/src
      run: .\make.bat
    # actions/upload-artifact drops executable bits; tar preserves mode bits in the archive.
    # See https://github.com/actions/upload-artifact/issues/38
    - name: Package toolchain (tar)
      if: inputs.toolchain == 'head'
      shell: bash
      run: |
        # The command below only considers .go files which are gitignored.
        # These must be files generated by make.bash. Other files don't need
        # to be packaged up because downstream jobs for tools/ or delve/ will
        # checkout the whole repo, so they'll have a copy of go/src etc. anyway.
        # Reducing the tarball size saves time on transfer, compression,
        # and GitHub Actions space utilization.
        git ls-files --ignored --exclude-standard -o -- ':(glob)go/**/*.go' | \
          xargs tar -czf go-head-${{ inputs.os }}.tgz go/bin go/pkg
    # actions/upload-artifact drops executable bits; tar preserves mode bits in the archive.
    # See https://github.com/actions/upload-artifact/issues/38
    - name: Package toolchain (tar)
      if: inputs.toolchain == 'gotip'
      shell: bash
      run: |
        # See https://github.com/golang/go/issues/61928#issuecomment-1673658972 ;
        # GOPROXY is read from go.env, so package that up.
        # go/src is included for access to stdlib APIs when compiling code
        # examples in Delve tests using gotip.
        tar -C go -czf go-gotip-${{ inputs.os }}.tgz bin pkg src go.env
    - uses: actions/upload-artifact@v6
      with:
        name: go-${{ inputs.toolchain }}-${{ inputs.os }}
        path: go-${{ inputs.toolchain }}-${{ inputs.os }}.tgz
